drop database VilsonSampaio;
create database VilsonSampaio;
use VilsonSampaio;

CREATE TABLE CLIENTE(
CPF_CLI BIGINT(11) PRIMARY KEY NOT NULL UNIQUE,
NOME_CLI VARCHAR(60) NOT NULL,
ENDERECO_CLI VARCHAR(100) NOT NULL,
TELEFONE_CLI BIGINT(13) NOT NULL
);
                   
CREATE TABLE FINANCEIRO(
CODIGO_FIN INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
DATA_FIN DATE NOT NULL, 
ENTRADA_FIN DOUBLE, 
SAIDA_FIN DOUBLE
);

CREATE TABLE FORNECEDOR(
CNPJ_FOR BIGINT(14) PRIMARY KEY NOT NULL UNIQUE, 
NOME_FOR VARCHAR(60) NOT NULL, 
ENDERECO_FOR VARCHAR(100) NOT NULL, 
TELEFONE_FOR BIGINT(13) NOT NULL
);

CREATE TABLE FUNCIONARIO(
CPF_FUN BIGINT(11) PRIMARY KEY NOT NULL UNIQUE, 
NOME_FUN VARCHAR(60) NOT NULL, 
FUNCAO_FUN VARCHAR(25) NOT NULL,
SALARIO_FUN DOUBLE NOT NULL
);


CREATE TABLE PEDIDO(
CODIGO_PED INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
DATA_PED DATE NOT NULL, 
STATUS_PED VARCHAR(45) NOT NULL, 
QUANTIDADE_PED INT NOT NULL,  
CPF_CLI BIGINT(11) NOT NULL REFERENCES CLIENTE,
CODIGO_PRODUTO INT NOT NULL REFERENCES PRODUTO, 
TOTAL_PED DOUBLE NOT NULL
);

CREATE TABLE PRODUTO(
CODIGO_PRODUTO INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
NOME_PRODUTO VARCHAR(45) NOT NULL, 
PRECO_PRODUTO DOUBLE NOT NULL
 );
 
 CREATE TABLE producao(
CODIGO_PRODUCAO INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
DATA_PRODUCAO DATE NOT NULL, 
QUANTIDADE_PRODUCAO INT NOT NULL,  
CODIGO_PRODUTO INT NOT NULL REFERENCES PRODUTO 
);

 CREATE TABLE estoque(
CODIGO_EST INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
QUANTIDADE_EST INT NOT NULL,  
CODIGO_PRODUTO INT NOT NULL REFERENCES PRODUTO 
);

select * from financeiro;
 

